"""Add more fields to Accommodation and Review

Revision ID: d20d8e1e2543
Revises: fef7d7ff1ee0
Create Date: 2024-08-26 22:23:08.414527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd20d8e1e2543'
down_revision: Union[str, None] = 'fef7d7ff1ee0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accommodations', sa.Column('default_price', sa.Integer(), nullable=False))
    op.add_column('accommodations', sa.Column('popularity_score', sa.Float(), nullable=False))
    op.add_column('accommodations', sa.Column('slug', sa.String(), nullable=False))
    op.add_column('accommodations', sa.Column('stars', sa.Integer(), nullable=False))
    op.add_column('accommodations', sa.Column('zoover_gold_award', sa.Boolean(), nullable=False))
    op.add_column('reviews', sa.Column('text', sa.String(), nullable=False))
    op.add_column('reviews', sa.Column('title', sa.String(), nullable=True))
    op.add_column('reviews', sa.Column('zoover_review_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'zoover_review_id')
    op.drop_column('reviews', 'title')
    op.drop_column('reviews', 'text')
    op.drop_column('accommodations', 'zoover_gold_award')
    op.drop_column('accommodations', 'stars')
    op.drop_column('accommodations', 'slug')
    op.drop_column('accommodations', 'popularity_score')
    op.drop_column('accommodations', 'default_price')
    # ### end Alembic commands ###
