"""Add score aspects to Review

Revision ID: fef7d7ff1ee0
Revises: 77e6cb01c08e
Create Date: 2024-08-25 19:12:38.524066

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fef7d7ff1ee0"
down_revision: Union[str, None] = "77e6cb01c08e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("reviews", sa.Column("child_friendly", sa.Float(), nullable=True))
    op.add_column("reviews", sa.Column("food", sa.Float(), nullable=True))
    op.add_column("reviews", sa.Column("hygiene", sa.Float(), nullable=True))
    op.add_column("reviews", sa.Column("location", sa.Float(), nullable=True))
    op.add_column("reviews", sa.Column("pool", sa.Float(), nullable=True))
    op.add_column("reviews", sa.Column("price_quality", sa.Float(), nullable=True))
    op.add_column("reviews", sa.Column("room", sa.Float(), nullable=True))
    op.add_column("reviews", sa.Column("service", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("reviews", "service")
    op.drop_column("reviews", "room")
    op.drop_column("reviews", "price_quality")
    op.drop_column("reviews", "pool")
    op.drop_column("reviews", "location")
    op.drop_column("reviews", "hygiene")
    op.drop_column("reviews", "food")
    op.drop_column("reviews", "child_friendly")
    # ### end Alembic commands ###
